apiVersion: v1
kind: Secret
metadata:
  name: database-credentials
  labels:
    app: database
type: Opaque
stringData:
  POSTGRES_DB: {{ .Values.database | quote }}
  POSTGRES_USER: {{ .Values.username | quote }}
  POSTGRES_PASSWORD: {{ .Values.password | quote }}
