frontend:
  image:
    repository: gskplatacrn73d5y.azurecr.io/three-tier/frontend
    tag: sha-46fa90f
  replicaCount: 1
  greeting: Hello from DEV
  resources:
    requests:
      cpu: 30m
      memory: 32Mi
    limits:
      cpu: 100m
      memory: 128Mi
  useConfigMapHTML: false
  blueGreen:
    enabled: true
    autoPromotionEnabled: true
    analysis:
      enabled: true
backend:
  image:
    repository: gskplatacrn73d5y.azurecr.io/three-tier/backend
    tag: sha-46fa90f
  replicaCount: 1
  echoMessage: backend response from dev
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi
  useEchoArgs: false
  env:
    APP_ENV: dev
    APP_VERSION: sha-46fa90f
  blueGreen:
    enabled: true
    autoPromotionEnabled: true
database:
  image:
    repository: postgres
    tag: 15-alpine
  database: appdb
  username: appuser
  password: dev-superSecret-change-me
  storage:
    size: 1Gi
    storageClass: managed-csi
  resources:
    requests:
      cpu: 50m
      memory: 256Mi
    limits:
      cpu: 250m
      memory: 512Mi
