apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
      annotations:
        sidecar.istio.io/proxyCPU: "10m"
        sidecar.istio.io/proxyCPULimit: "100m"
        sidecar.istio.io/proxyMemory: "64Mi"
        sidecar.istio.io/proxyMemoryLimit: "256Mi"
    spec:
      containers:
        - name: backend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "-text={{ .Values.echoMessage }} (ns={{ .Release.Namespace }})"
            - "-listen=:{{ .Values.service.port }}"
          ports:
            - containerPort: {{ .Values.service.port }}
              name: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.port }}
            initialDelaySeconds: 2
            periodSeconds: 5
